### ISSUE TITLE
name 'EvalMetric' is not defined

### ISSUE THREAD

**Issue by Hsiungmy** [saicoco/mxnet-siamese#1]
hi,when I run the code I met a problem,the error was :name 'EvalMetric' is not defined
.The whole error was displayed below:
![image](https://cloud.githubusercontent.com/assets/10348961/25229835/6194e73c-2604-11e7-98a7-4c5dbc06a894.png)
I had checked the name 'EvalMetric' but have no outcomes.I will be happy if you can see this question and give me a feedback.
Thanks.

**Comment by saicoco** [comment]
Now it works, the siamise_metric is extend from `mx.metric.EvalMetric`
